name: Cypress Tests

on:
  push:
    branches:
      - main  # Executa os testes quando houver um push na branch main
  pull_request:
    branches:
      - main  # Executa os testes em cada PR para a branch main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          npm install
          npm install --save-dev mochawesome-merge

      - name: Executar testes do Cypress
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        run: |
          npx cypress run --spec "cypress/e2e/api/**" \
            --reporter mochawesome \
            --reporter-options "reportDir=cypress/report/api,overwrite=false,html=true,json=true"

          npx cypress run --spec "cypress/e2e/front/**" \
            --reporter mochawesome \
            --reporter-options "reportDir=cypress/report/front,overwrite=false,html=true,json=true"

      - name: Mesclar relatórios
        run: npx mochawesome-merge "cypress/report/**/.json" > cypress/report/merged-report.json

      - name: Salvar Relatório Consolidado
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: cypress/report
          retention-days: 5