name: Cypress Tests

on:
  push:
    branches:
      - main  # Executa os testes quando houver um push na branch main
  pull_request:
    branches:
      - main  # Executa os testes em cada PR para a branch main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          npm install
          npm install -g allure-commandline --save-dev

      - name: Run Cypress tests
        run: npm run cypress:run 

      - name: Generate Allure Report
        run: |
          allure generate cypress/results/allure --clean -o cypress/results/allure-report
          allure open cypress/results/allure-report 

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress/results/allure-report     